### ISSUE TITLE
재귀 강의 블로그 글 관련입니당

### ISSUE THREAD

**Issue by J-Shine** [encrypted-def/basic-algo-lecture-metarial#1]
안녕하세요 바킹독님 항상 강의 잘 보고 있습니다 ㅎㅎ 정말로 배우는게 많아요 감사합니다 
재귀 강의를 보다가 오타를 조금 발견해서 알려드려요
https://blog.encrypted.gg/943
이곳에서 ppt 11페이지 설명 중 m이 232보다 크다면 이라고 되어있는데 2^32에서 오타가 나신 것 같아요
그리고 ppt 18페이지 밑 하노이탑 코드 주소가 ~~11729.cpp로 링크가 걸려있는데 깃허브 주소는 ~~11729,cpp이라 링크가 작동하지 않아요

앞으로도 좋은강의 부탁드립니다 감사합니당 ㅎㅎ

**Comment by encrypted-def** [comment]
앗 안녕하세요 J-Shine님, 알려주신 두 부분 수정했습니다. 감사합니다 좋은 하루 보내세요 ^_____^
